#!/bin/bash

systemctl stop openshift-node
systemctl stop openshift-master
rm -rf /var/lib/openshift/.openshift.local.etcd/
cp -a /var/lib/openshift/openshift.local.etcd/ /var/lib/openshift/.openshift.local.etcd/
docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
docker rmi $(docker images | awk '/<none>/ { print $3 }')
systemctl start openshift-node
systemctl start openshift-master
sleep 10
oadm registry --config=/etc/openshift/master/admin.kubeconfig --credentials=/etc/openshift/master/openshift-registry.kubeconfig --images='registry.access.redhat.com/openshift3/ose-${component}:${version}'
oadm router   --config=/etc/openshift/master/admin.kubeconfig --credentials=/etc/openshift/master/openshift-router.kubeconfig   --images='registry.access.redhat.com/openshift3/ose-${component}:${version}'
