apiVersion: v1
kind: Template
metadata:
  name: nexus
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    selector:
      name: ${APPLICATION_NAME}
    replicas: 1
    template:
      metadata:
        labels:
          name: ${APPLICATION_NAME}
      spec:
        containers:
        - image: ${NEXUS_IMAGE}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          volumeMounts:
          - mountPath: /sonatype-work
            name: sonatype-work
        volumes:
        - name: sonatype-work
          persistentVolumeClaim:
            claimName: sonatype-work
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: nexus
  spec:
    dockerImageRepository: sonatype/nexus
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      deploymentconfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: sonatype-work
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
parameters:
- name: APPLICATION_NAME
  required: true
  value: nexus
- description: Volume space available for data, e.g. 512Mi, 2Gi
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
