Vagrant.configure(2) do |config|
  
  config.vm.define "master" do |master|
    master.vm.box = "rhel-7.1"
    master.vm.network :private_network, ip: "192.168.232.101"
    master.vm.provision "shell", path: "vagrant-provision.sh", args: "master"
    master.vm.provider "libvirt" do |libvirt|
      libvirt.driver = "kvm"
      libvirt.memory = 1024
      libvirt.cpus = 4
      libvirt.storage :file, :size => '10G'
    end
  end

  config.vm.define "node01" do |node01|
    node01.vm.box = "rhel-7.1"
    node01.vm.provision "shell", path: "vagrant-provision.sh", args: "node01"
    node01.vm.network :private_network, ip: "192.168.232.201"
    node01.vm.provider "libvirt" do |libvirt|
      libvirt.driver = "kvm"
      libvirt.memory = 1024
      libvirt.cpus = 4
      libvirt.storage :file, :size => '10G'
    end
  end

  config.vm.define "node02" do |node02|
    node02.vm.box = "rhel-7.1"
    node02.vm.provision "shell", path: "vagrant-provision.sh", args: "node02"
    node02.vm.network :private_network, ip: "192.168.232.202"
    node02.vm.provider "libvirt" do |libvirt|
      libvirt.driver = "kvm"
      libvirt.memory = 1024
      libvirt.cpus = 4
      libvirt.storage :file, :size => '10G'
    end
  end

end
