apiVersion: v1
kind: Template
metadata:
  name: custom-router
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: custom-router
      git:
        uri: https://github.com/nekop/openshift-sandbox
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ose-haproxy-router:v3.1.1.6
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ose-haproxy-router
  spec:
    dockerImageRepository: registry.access.redhat.com/openshift3/ose-haproxy-router
parameters:
- name: APPLICATION_NAME
  required: true
  value: custom-router
